mariadb:
  image:
    debug: true
  auth:
    rootPassword: "password"
    database: databaseName

back:
  image:
    repository: registry.gitlab.com/username/repo_name
    pullPolicy: IfNotPresent
    tag: "latest-back"

  imagePullSecrets:
    - name: gitlab-registry

  service:
    type: NodePort
    port: 80
    nodePort: 30001

front:
  image:
    repository: registry.gitlab.com/username/repo_name
    pullPolicy: IfNotPresent
    tag: "latest-front"

  imagePullSecrets:
    - name: gitlab-registry

  service:
    type: NodePort
    port: 80
    nodePort: 30002